# -*- coding: utf-8 -*-
"""Playstore_PySpark

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HXMtB48Id1vpnO1Sn6C_y202YY3Owrrc
"""

#pip install pyspark

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import pyspark
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType,StructField, StringType, IntegerType
from pyspark.sql.functions import *

spark = SparkSession.builder.appName('GooglePlayStoreAnalysis').getOrCreate()

from re import escape
df= spark.read.csv('googleplaystore.csv',header=True,inferSchema=True, sep = ',', escape = '"')

df.count()

df.show(1)

df = df.drop("size","Content Rating", "Last Updated","Current Ver", "Android Ver")

df.head()

df.show()

df = df.withColumn("Reviews", df["Reviews"].cast("int"))\
      .withColumn("Installs", regexp_replace("Installs", "[^0-9]", "").cast("int"))\
      .withColumn("Price", regexp_replace("Price", "[$]", "").cast("float"))

df.show()

df.createOrReplaceTempView("googleplaystore")

"""**Top 10 apps with highest reviews**"""

sql_1= spark.sql("select App, sum(Reviews) from googleplaystore group by App order by sum(Reviews) DESC Limit 10  ")

sql_1.show()

sql_pd = sql_1.toPandas()

plt.bar(sql_pd['App'], sql_pd['sum(Reviews)'])
plt.xticks(rotation=45)
plt.xlabel('App')
plt.ylabel('Reviews')
plt.title('Top 10 Apps with Highest Reviews')
plt.show()

"""**Top 10 installed Apps**"""

sql_2 = spark.sql("select App, Type, sum(Installs) from googleplaystore group by App, Type order by sum(Installs) DESC Limit 10  ")
# Added 'Type' to the GROUP BY clause to include it in the grouping

sql_2.show()

sql_pd_2 = sql_2.toPandas()

sns.countplot(data=sql_pd_2, x='App')
plt.xticks(rotation=45)
plt.title('Top 10 Installed Apps')
plt.show()

"""**top 10 Paid Apps **"""

sql_3 = spark.sql("select App, sum(Installs) from googleplaystore where Type = 'Paid' group by App order by sum(Installs) DESC Limit 10  ")

sql_3.show()

"""**Top Paid Rating apps**"""

sql_4 = spark.sql("select App, sum(Installs) from googleplaystore where Type = 'Paid' and Rating > 4.5 group by App order by sum(Installs) DESC Limit 10  ")

sql_4.show()

sql_4_pd = sql_4.toPandas()

GroupedData = sql_4_pd['App'].value_counts()
plt.figure(figsize=(7,7))
plt.pie(GroupedData, labels=GroupedData.index, autopct='%1.1f%%')
plt.title('Top Paid Rating Apps')
plt.show()

